print("=" * 60)
print("🛰️  SPOT PROJECT QUICK START")
print("=" * 60)
print("\n📁 Project files created in: /home/miko/Documents/SPOT_Project/")
print("\n✅ Available resources:")
print("   1. SPOT_QGIS_Workflow.md - Complete guide")
print("   2. quick_reference.md - Cheat sheet") 
print("   3. spot_processing_tools.py - Python functions")
print("   4. toulouse_spot_analysis.py - Toulouse workflow")
print("\n⚡ Quick Commands:")
print("\n# Load Toulouse analysis tools:")
print("exec(open('/home/miko/Documents/SPOT_Project/toulouse_spot_analysis.py').read())")
print("\n# Load generic SPOT tools:")
print("exec(open('/home/miko/Documents/SPOT_Project/spot_processing_tools.py').read())")
print("\n🚀 To start:")
print("1. Restart QGIS (for plugins to activate)")
print("2. Run: exec(open('/home/miko/Documents/SPOT_Project/toulouse_spot_analysis.py').read())")
print("3. Load your SPOT image")
print("4. Use: process_spot_image(iface.activeLayer())")
print("\n💡 Pro tip: Keep quick_reference.md open while working!")
print("=" * 60)
