#!/bin/bash
# Display all available map interfaces

echo "🗺️  SPOTS SECRETS OCCITANIE - MAP INTERFACES"
echo "============================================"
echo ""
echo "📍 AVAILABLE MAPS:"
echo ""
echo "1️⃣ IGN OFFICIAL MAP (NEW!)"
echo "   http://localhost:8085/ign-official-map.html"
echo "   ✓ Official French government maps"
echo "   ✓ Elevation data on click"
echo "   ✓ Address geocoding"
echo "   ✓ Department boundaries"
echo ""
echo "2️⃣ REGIONAL MAP"
echo "   http://localhost:8085/regional-map.html"
echo "   ✓ Department-based navigation"
echo "   ✓ Zone exploration"
echo "   ✓ Regional statistics"
echo ""
echo "3️⃣ PREMIUM MAPS"
echo "   http://localhost:8085/premium-map.html"
echo "   ✓ Multiple map providers"
echo "   ✓ Satellite views"
echo "   ✓ Specialized outdoor maps"
echo ""
echo "4️⃣ ENHANCED MAP"
echo "   http://localhost:8085/map-enhanced.html"
echo "   ✓ Advanced controls"
echo "   ✓ Weather integration"
echo "   ✓ Drawing tools"
echo ""
echo "🔥 RECOMMENDED: Try the new IGN Official Map!"
echo "   Best quality for French territory"
echo ""
echo "📊 API ENDPOINTS:"
echo "   • Base API: http://localhost:8000"
echo "   • API Docs: http://localhost:8000/docs"
echo "   • All Spots: http://localhost:8000/api/spots"
echo "   • By Department: http://localhost:8000/api/spots/department/{code}"
echo "   • Statistics: http://localhost:8000/api/stats"
