#!/bin/bash
# Display available premium map information

echo "🗺️  PREMIUM MAP PROVIDERS NOW AVAILABLE"
echo "======================================="
echo ""
echo "🇫🇷 FRENCH OFFICIAL MAPS (Best for Toulouse):"
echo "  • IGN Satellite - Ultra high-resolution official French satellite imagery"
echo "  • IGN Cartes - Official French topographic maps with trails & terrain"
echo ""
echo "🛰️ SATELLITE IMAGERY:"
echo "  • ESRI World Imagery - Professional grade, regularly updated"
echo "  • Sentinel-2 Cloudless - ESA satellite composite without clouds"
echo ""
echo "🥾 OUTDOOR ACTIVITIES:"
echo "  • OpenTopoMap - Detailed elevation and terrain features"
echo "  • Stadia Outdoors - Optimized for hiking and outdoor sports"
echo "  • CyclOSM - Specialized cycling map with bike routes"
echo ""
echo "🎨 STYLE OPTIONS:"
echo "  • CARTO Dark Matter - Dark theme for comfortable viewing"
echo "  • CARTO Positron - Clean, minimal light theme"
echo "  • CARTO Voyager - Colorful and detailed"
echo ""
echo "📍 ACCESS THE PREMIUM MAP:"
echo "  http://localhost:8085/premium-map.html"
echo ""
echo "✨ Features:"
echo "  • No API keys required for most providers"
echo "  • French IGN maps are completely free"
echo "  • Smooth switching between map types"
echo "  • Clustered markers for 3,226 spots"
echo "  • Mobile responsive design"
