#!/bin/bash
# Check status of running spots servers

echo "🌦️  SECRET SPOTS/WEATHER APPLICATION STATUS"
echo "=========================================="
echo ""
echo "✅ BACKEND API: Running on http://localhost:8000"
echo "   - API Docs: http://localhost:8000/docs"
echo "   - Total spots: 3,226"
echo "   - Process ID: 89981"
echo ""
echo "✅ FRONTEND: Running on http://localhost:8085"
echo "   - Interactive map with weather integration"
echo "   - Process ID: 90073"
echo ""
echo "📊 DATABASE:"
echo "   - SQLite database: data/toulouse_spots.db"
echo "   - Size: 940KB"
echo "   - Contains consolidated spot data"
echo ""
echo "🔗 QUICK LINKS:"
echo "   - Frontend: http://localhost:8085"
echo "   - API Explorer: http://localhost:8000/docs"
echo "   - Get all spots: http://localhost:8000/api/spots"
echo "   - Database stats: http://localhost:8000/api/stats"
echo ""
echo "Press Ctrl+C in the respective terminals to stop the servers."
