#!/bin/bash
# Google Maps API Quick Setup for SPOTS Project
# Gets you 28,000 free geocoding requests per month ($200 credit)

echo "🗺️ GOOGLE MAPS API QUICK SETUP"
echo "================================"
echo ""
echo "🎯 GOAL: Get 714 more addresses for your spots!"
echo "💰 COST: FREE ($200/month credit = 28,000 requests)"
echo ""
echo "📋 STEP-BY-STEP SETUP:"
echo ""
echo "1️⃣ GO TO GOOGLE CLOUD CONSOLE:"
echo "   👉 https://console.cloud.google.com/"
echo ""
echo "2️⃣ CREATE NEW PROJECT:"
echo "   • Click 'New Project'"
echo "   • Name: 'SPOTS-Enrichment'"
echo "   • Click 'Create'"
echo ""
echo "3️⃣ ENABLE APIS:"
echo "   • Go to 'APIs & Services' > 'Library'"
echo "   • Search and enable: 'Geocoding API'"
echo "   • Search and enable: 'Places API' (optional)"
echo ""
echo "4️⃣ CREATE API KEY:"
echo "   • Go to 'APIs & Services' > 'Credentials'"
echo "   • Click '+ CREATE CREDENTIALS' > 'API key'"
echo "   • Copy your API key"
echo ""
echo "5️⃣ ADD TO YOUR PROJECT:"
echo "   • Add to .env file: GOOGLE_MAPS_API_KEY=your_key_here"
echo ""
echo "🚀 EXPECTED RESULTS:"
echo "   • 714 missing addresses → 90%+ coverage"
echo "   • High-quality global geocoding"
echo "   • Place details and metadata"
echo ""
echo "💡 FREE TIER LIMITS:"
echo "   • $200 free credit per month"
echo "   • = 28,000 geocoding requests"
echo "   • = Enough for your 714 spots + future growth"
echo ""
echo "⚡ SETUP TIME: ~5 minutes"
echo "💪 IMPACT: Massive data quality improvement!"
